### ISSUE TITLE
Question about Algorithm 2 in the paper

### ISSUE THREAD

**Issue by bingxuezhiya** [NetManAIOps/Squeeze#2]
Hello, I am trying to implement Squeeze by myself these days for my research project. My implement is base on the paper but I faced some problems on Algorithm 2.
The description of following variables is quiet confusing as to iterate the whole possible attribute combinations of a cuboid it will cost n^m times. This is no better than a brute force algorithm.

n_ele ← the number of leaf attribute combinations descended from each attribute combination of cuboid in cluster
n_descents ← the number of all leaf attribute combinations descended from each attribute combination of cuboid

Assume we have 5 attributes which there are 4 choices for each. So there will be nealy 1k possible combinations when iterate in a deep layer. (We start from lower layer with only one attribute)

Can you explain those more clearly? Some examples will be a lot of help.
Thanks

**Comment by lizeyan** [comment]
Yes, in Algorithm 2 we have to traverse  all leaf attribute combination. But there are two misunderstandings.
1. According to our experience, most data are extremely sparse, which means most leaf attribute combinations will never appear. For example, if there are two attributes: country and province, <USA, Beijing> will never appear. Although there are nearly 200 countries and thousands of provinces, the actual number of attribute combinations is not just the production of the number of each attribute's choice.
2. Traversing  all leaf attribute combination is not the same as brute force algorithm. By our definition, a root cause can be a set of any number of attribute combinations.   Take Table.1 as an example, there are 9 leaf attribute combinations, but there are 2^(2+7+9-1) potential root causes. A brute force algorithm should search from all 2^(2+7+9-1) candidates, but Squeeze does not.

**Comment by bingxuezhiya** [comment]
I get your point. So the question changes to how to calculate n_ele and n_descents. As we iterate remain leaf combinations (after knee point filter) instead of possible leaves. The description for n_ele and n_descents are quiet confusing for me.
For example as shown in Table 1, we iterate province as the first cuboid. What will be n_ele and n_descents for first leaf combination? 
And based on you answer, we iterate based on leaf we have instead of possible combinations of cuboid. Does it means that the participants of sort in the next step are just leaves in current cluster? What if for current cuboid some leaves are same.(Like first and second records in Table 1 on cuboid province)
Thanks for your answer

**Comment by lizeyan** [comment]
For example, we have a DataFrame `df` as follows:
index, A, B
1,a1,b1
2,a2,b2
3,a1,b2
4,a2,b1
And the current cluster is `indices=[1, 3]`
So for cuboid A, the elements are [a1, a2]
so
``` python
cluster_attribute_combinations = df[indices] # we will get [('a1', 'b1'), ('a1', 'b2')]
elements_in_this_cluster = keep_attribute('A', cluster_attribute_combinations)  # we will get ['a1', 'a1']
unique_elements, n_ele = np.unique(elements_in_this_cluster, return_counts=True)
``` 
and
```
n_descent = df.groupby('A').count()
```
The code above is just an illustration, or pseudocode.
